language: node_js

node_js:
    - 12

sudo: required

script:
    - sudo apt-get install -y libstdc++6
    - sudo apt-get install -y sqlite3 libsqlite3-dev
    - npm install -g node-gyp --build-from-source &> /dev/null
    - npm install sqlite3 --build-from-source &> /dev/null
    - npm install yarn
    - yarn install
    - yarn run test

branches:
  only:
  - gh-pages
  - /.*/
