language: node_js

node_js:
  - 12

sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

script:
  - sudo apt-get install -y libstdc++6
  - sudo apt-get install -y sqlite3 libsqlite3-dev
  - npm ci
  - npm install sqlite3 --build-from-source &> /dev/null
  - npm run test

branches:
  only:
  - gh-pages
  - /.*/
