language: node_js
dist: xenial

node_js:
    - 12

sudo: required

script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get install libstdc++6-4.7-dev -y
    - sudo apt-get install -y sqlite3 libsqlite3-dev
    - npm install -g node-gyp --build-from-source &> /dev/null
    - npm install sqlite3 --build-from-source
    - npm ci
    - npm run test

branches:
  only:
  - gh-pages
  - /.*/
