language: node_js

node_js:
  - 12

script:
  - sudo apt-get install -y libstdc++6
  - sudo apt-get install -y sqlite3 libsqlite3-dev
  - npm ci
  - npm install sqlite3 --build-from-source
  - npm run test

branches:
  only:
  - gh-pages
  - /.*/
